import { Button, Flex, Text, useDisclosure } from "@chakra-ui/react";

import { useDeviceSize } from "../../../../hooks/useDeviceSize";
import EnableMFAModal from "../../../../components/Modals/EnableMFAModal";

export default function EnableTwoFactorAuth() {
  const { isMobile } = useDeviceSize();
  const enableMFAModalDisclosure = useDisclosure();

  return (
    <>
      <Flex px="2" py="6" w="full" flexDirection="column" alignItems="center">
        <Flex flexDirection="column" gap="4" w={isMobile ? "full" : "60%"}>
          <Text fontSize="sm" fontWeight="semibold">
            Protect your account with an extra layer of security. Once set up,
            when logging in you will be prompted to provide a code generated by
            an authenticator app on your phone or tablet.
          </Text>
          <Button
            colorScheme="brand"
            title="Configure MFA"
            onClick={() => enableMFAModalDisclosure.onOpen()}
          >
            Configure MFA
          </Button>
        </Flex>
      </Flex>
      <EnableMFAModal {...enableMFAModalDisclosure} />
    </>
  );
}
