name: Deploy Application
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

jobs:
  deploy-frontend:
    name: Deploy Frontend
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.13.x"
          cache: "yarn"
          cache-dependency-path: "./frontend/yarn.lock"
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4.0.0
        with:
          role-to-assume: arn:aws:iam::585984234158:role/upstairs-deployment-pipeline
          aws-region: us-east-2
          retry-max-attempts: 10
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build application
        run: yarn build
        env:
          VITE_AWS_COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          VITE_AWS_COGNITO_CLIENT_ID: ${{ secrets.AWS_COGNITO_CLIENT_ID }}
      - name: Deploy application to S3
        run: aws s3 cp --recursive ./dist/ s3://upstairs-frontend-bucket/
